### ISSUE TITLE
issue with postprocess.py for aerial dataset

### ISSUE THREAD

**Issue by amardeepjaiman** [Oslandia/mapillary_classification#126]
Hi,

In extract_coordinates_from_filenames(filenames): function, coordinates cant be decoded from tile_image_name using below code.
basenames = [os.path.splitext(os.path.basename(f))[0] for f in filenames]
coordinates = [b.split("_")[-2:] for b in basenames]
return [[int(x), int(y)] for x, y in coordinates]

For aerial dataset, the tile names are "austin14_10.png". the above code can not work with this naming convention. I think this code was written for Tanzania dataset. Can someone guide how to get x,y value from this naming convention ?

Thanks,
Amardeep

**Comment by delhomer** [comment]
Thank you for pointing this issue! You're totally right, that is a urgent point to address.

We should modify the way `aerial` datasets are preprocessed, so as to make them similar to `tanzania` dataset. That's looks related to #91. I add this to my todo list.
