### ISSUE TITLE
Data Generation (Preprocessing) Issue

### ISSUE THREAD

**Issue by AhmadAmmar** [Oslandia/mapillary_classification#139]
I executed the data generation (preprocessing) script, but the tiled label images are coming out to be plain black. What could I be doing wrong?

`deepo datagen -D aerial -s 224 -P /media/splash/00F2D259F2D25310/Data -t 180 -v 15 -T 229`

![Screenshot from 2019-05-24 23-44-13](https://user-images.githubusercontent.com/9590856/58349884-e46ef700-7e7d-11e9-8492-4338f8d15346.png)

**Comment by delhomer** [comment]
Hi @AhmadAmmar,

Thanks for posting this issue. You just got a bug that comes from the `Aerial` dataset label format. I probably broke the aerial dataset generation when tackling the dataset standardization. I'm working on a fix!

**Comment by delhomer** [comment]
@AhmadAmmar it should be OK now, do not hesitate to reopen the issue if needed!
