### ISSUE TITLE
data augmentation/transformation while training

### ISSUE THREAD

**Issue by amardeepjaiman** [Oslandia/mapillary_classification#141]
In the current implementation, i dont see any provision for data transformation or augmentation while training. is it possible to add some data transformation steps in training script ?

**Comment by delhomer** [comment]
Depending on the dataset you use, there are some data augmentation techniques. We do horizontal and vertical flips for `Aerial` and `Tanzania` datasets. We could do horizontal flips for Mapillary as well, even if it is not currently implemented.

Should you be interested in data augmentation, such an improvement can be implemented in the `_preprocess` method of different dataset classes (see [Tanzania case](https://github.com/Oslandia/deeposlandia/blob/master/deeposlandia/datasets/tanzania.py#L85) for example).

**Comment by amardeepjaiman** [comment]
I saw the source code of aerial.py, But I could not see any augmented images in the dataset generated.  Because datagen.py arguments need number of training images which needs to be generated to be mentioned and If i pass number of training tiles to be generated then will it augment or not ?

means if i have 5000x5000 tiles and i cut 500x500 size tiles, then it should generate 100 images(tiles) for training. So if i pass -t=100 then it will generate 100 tiles only . Will they be randomly augmented or I need to pass -t=150 or something to generate the augmented images ?

Please clarify.

**Comment by delhomer** [comment]
@amardeepjaiman do you use an up-to-date version of the code? I recently pushed some fixes on this dataset. You should be able to generate augmented patches saved as `name_width_height_x_y_corner.png` (`austin1_400_400_100_200_nw.png` for example is a 400*400 patch generated from `austin1.tif`; its upper-left corner being located at (100,200) in the original image). Horizontal flips are characterized by the `_ne` suffix (resp. `_sw` for vertical flips, and `_se` for horizontal+vertical flips).

By default, we generate 4 images for each original image crop when there is at least one building (no data augmentation in case of empty image).

Regarding the image quantity, we used a home-made heuristic (*translation: certainly far from the best way of doing, however a choice had to be made...*).

The image quantity arguments should be used as follows:
- training and validation image amounts represent an estimation of the desired total number, spread on all raw images (let say you have 10 raw images, and you ask for 1000 images; the program will try to generate 100 png tiles for each raw images; if the raw image is kind of empty, another stopping criterion related to candidate crops is used --the loop is exited after 2*100 attempts).
- testing data: we just build grids for as many raw images as indicated by the argument, considering the requested image size. Hence with 500x500 tiles, and 10 requested images, in a folder that contains 5000x5000 images, you will get 10*100 tiles.
