### ISSUE TITLE
Aerial Dataset Presentation - Dataset Handling

### ISSUE THREAD

**Issue by AhmadAmmar** [Oslandia/mapillary_classification#143]
Code:

`input_folder = utils.prepare_input_folder(DATAPATH, DATASET)
preprocess_folder = utils.prepare_preprocessed_folder(DATAPATH, DATASET, 224, "full")`

Output:

TypeError                                 Traceback (most recent call last)
<ipython-input-8-227d6bb77f9a> in <module>
      1 input_folder = utils.prepare_input_folder(DATAPATH, DATASET)
----> 2 preprocess_folder = utils.prepare_preprocessed_folder(DATAPATH, DATASET, 224, "full")

TypeError: prepare_preprocessed_folder() takes 3 positional arguments but 4 were given

![Screenshot from 2019-06-03 17-57-05](https://user-images.githubusercontent.com/9590856/58803675-7c60a380-8629-11e9-8e17-cb804c9e43fe.png)

**Comment by delhomer** [comment]
Hi @AhmadAmmar,

Thanks for the bug insight. Indeed this should have been modified with the last major modification of the dataset. However, a fix has been committed recently (*cf* commit [07c1913](https://github.com/Oslandia/deeposlandia/commit/07c191332d87fa3f89d98570f1a9b4549117bff2)). Everything should be OK now.

Could you confirm that it is fine for you?

**Comment by delhomer** [comment]
No update there since a long time, I close the issue.
