### ISSUE TITLE
Write a summary() method

### ISSUE THREAD

**Issue by delhomer** [Oslandia/mapillary_classification#18]
Write a `summary()` method inspired from Keras API. The aim is to get a printable version of the neural network, that provides information about the numbers of layers and parameters in the network.

**Comment by garaud** [comment]
Or you turn the current implementation with TensorFlow into a Keras implementation! :)

**Comment by delhomer** [comment]
Not sure the amount of work is the same... ;)
We could just call Keras API for this feature, but I'm not sure it's possible.

**Comment by garaud** [comment]
We also can look at the Keras implementation 
https://github.com/keras-team/keras/blob/master/keras/utils/layer_utils.py#L24

**Comment by delhomer** [comment]
In theory, this issue will be fixed in parallel with issue #29 .

**Comment by delhomer** [comment]
This issue is obsolete as we moved to Keras API, which contains a `summary()` function. I close this issue.
