### ISSUE TITLE
Introduce semantic segmentation in the project

### ISSUE THREAD

**Issue by delhomer** [Oslandia/mapillary_classification#19]
A more ambitious kind of image detection problem is semantic segmentation, *i.e.* the association of each pixel with a class of the glossary, so as to get a fully-labeled picture (see [Mapillary dataset](https://www.mapillary.com/dataset/vistas?lat=20&lng=0&z=1.5), and some examples in this [repo](https://github.com/Oslandia/streetscene_CNN/tree/master/images)).

Other state-of-the-art models exist in this way, one can refer for instance to [SEC](https://github.com/kolesman/SEC) or [Mask-RCNN](https://github.com/matterport/Mask_RCNN).

**Comment by garaud** [comment]
Can this issue be closed with the recent pull request #15 ? Or can you prefer waiting for the "true" semantic segmentation integration in the `models.py` module?

**Comment by delhomer** [comment]
We may close this one, as it is related to the "introduction" of semantic segmentation. And re-open another (others) issues progressively if needed.
