### ISSUE TITLE
Update shape dataset definition

### ISSUE THREAD

**Issue by delhomer** [Oslandia/mapillary_classification#20]
The shape dataset has to be extended to labeled images, *i.e.* labeled version of each image must be produced during dataset population, and corresponding file path must be integrated into the dataset structure stored as a `json` file.

This work has still be done for Mapillary dataset.

**Comment by garaud** [comment]
This issue deals with the possibility to carry out semantic segmentation with the *shapes* dataset?

**Comment by delhomer** [comment]
That's it. Currently there are no "label_filename" key in main dictionary. The point is to add such a key during dataset population, and to generate the associate labeled images on the file system.
