### ISSUE TITLE
Implementation of the IoU (Intersection over Union) function for metrics and/or loss

### ISSUE THREAD

**Issue by garaud** [Oslandia/mapillary_classification#21]
This function can be used as a metrics or loss function.

See:
* https://www.pyimagesearch.com/2016/11/07/intersection-over-union-iou-for-object-detection/
* http://angusg.com/writing/2016/12/28/optimizing-iou-semantic-segmentation.html

**Comment by delhomer** [comment]
Fixed after PR #75 merging. I close it.
