### ISSUE TITLE
Thoughts about the input/ouput folders structure and design experiment

### ISSUE THREAD

**Issue by garaud** [Oslandia/mapillary_classification#23]
I think we should separate the input and output folders which can share the same root directory, e.g. `root_dir = '../data/streetscene'`.

* input folder with the raw datasets
  - `input/mapillary` where you can find the `tranining` and `validation` folders and the further preprocess folders (resized and/or aggregated images)
  - `input/shapes`

* output folder with the different output result for the different dataset
  - `output/mapillary`
  - `output/shapes`

and create a folder for each run. A number of parameter names and the date can occur in the folder name. A meta.json or YAML file inside this folder which summarizes the list of input parameters and hyptohesis.

**Comment by delhomer** [comment]
I'm not sure it is necessary to add another step in the system file tree. IMHO, the clearest way, that is relatively close than the current way (from `sources` repo):
- ../data
  - mapillary/
    - input/
      - config.json
      - training/
      - validation/
      - testing/
    - preprocessed/
      - `imagesize`_`full|aggregated`/ (`full` = not aggregated)
        - config.json
        - training/
        - validation/
        - testing/
    - output/
      - feature_detection/
        - log/ (contains TensorBoard graph => my `graph` repo, however it is better to call it `log`, I agree)
          - `instancename`-`imagesize`-`networksize`-`learningrate`-`batchsize`-`learningstep`-...
            - training
            - validation (both are distinguished for TensorBoard monitoring)
        - checkpoints/ (saved model)
          - `instancename`-`imagesize`-`networksize`-`learningrate`-`batchsize`-`learningstep`-...
        - results/ (main metrics, certainly is the meta.json/YAML)
          - `instancename`-`imagesize`-`networksize`-`learningrate`-`batchsize`-`learningstep`-...
        - chronos/
          - `instancename`-`imagesize`-`networksize`-`learningrate`-`batchsize`-`learningstep`-...
      - semantic_segmentation/
        - ...
      - `problem`/
        - ...
  - shapes/
    - ...
  - `dataset`/
    - ...

A preprocessed dataset is charactered only by the image size, I guess. And of course by the fact that its labels are aggregated or not.

The output are distinguished by the arguments that will enter into a clean experiment set, the indicated list is not concise.

We thus have: 
- the dataset
- the step of the process (input, preprocessing, output)
- the dataset nature (training, validation, testing)
- the research problem
- the complete instance name

**Comment by garaud** [comment]
Your structure looks great! What do you mean about `instancename`? This is a name of the run when you launch `train.py`? Of the name of the model to launch?

**Comment by delhomer** [comment]
Just the name of the run, indeed. I do not use it actually (I mean, I just call mapillary run `mapil` or whatever, and shape run `shape`...), however it is a possible way to tackle multiple runs for a same set of parameters. (To stay simple, there is this way, and the date way.)
