### ISSUE TITLE
Make a setup.py

### ISSUE THREAD

**Issue by garaud** [Oslandia/mapillary_classification#31]
Also find a name for the package. Some propositions:

- `from street.models import Segmentation`
- `from deeposlandia.models import Segmentation`
- `from streetscene.models import Segmentation`
- `from street_scene.models import Segmentation`

Note that the **shapes** dataset doesn't deal with street scene images. Is is relevant to name it "street*something"?

**Comment by delhomer** [comment]
Ok to drop "street" from the package name. And from the project name as a consequence.
I like `deeposlandia`, we can imagine some other variants:
- `deeplandia`
- `oslanndia`
- `cnnlandia`
- `oslandcnn`
...

**Comment by garaud** [comment]
I close this one.
