### ISSUE TITLE
Write unit tests

### ISSUE THREAD

**Issue by delhomer** [Oslandia/mapillary_classification#36]
Take advantage of the code refactoring to design unit tests concurrently with new API design.

What to test:
- [x] layers (convolution, maxpooling, dense, transposed_convolution)
- [x] dataset creation
- [x] dataset population
- [x] model creation
- [x] model training
- [x] model inference
- [x] model backup

**Comment by garaud** [comment]
Can we close that?

**Comment by delhomer** [comment]
I change the description of the issue, as it planned to design tests for a wide range of functionnalities. I propose to maintain a checkbox list, as we go along the issue resolution.

**Comment by delhomer** [comment]
All the listed tests have been added. I close this issue, and suggest that new tests will have to be added gradually with new code.
