### ISSUE TITLE
Avoid some warning messages about elementwise operations

### ISSUE THREAD

**Issue by garaud** [Oslandia/mapillary_classification#44]
When I launch the test with `pytest`, I've got these messages:

```
=================== warnings summary =========================
tests/test_generators.py::test_featdet_shape_generator
  deeposlandia/deeposlandia/generator.py:24: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
    mask = img == label

tests/test_generators.py::test_semseg_shape_generator
  deeposlandia/deeposlandia/generator.py:49: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
    mask = img == label

-- Docs: http://doc.pytest.org/en/latest/warnings.html
```

**Comment by delhomer** [comment]
These warnings arise during the label generator creation. It seems that they are numpy-related. Have you got an idea of how to solve this?

**Comment by garaud** [comment]
I think we'll try to find out the origin of the message: what file,
where, ... to better understand what it's about.

Maybe use a numpy test utils assertion function for that.
Raphael Delhome writes:

> These warnings arise during the label generator creation. It seems that
> they are numpy-related. Have you got an idea of how to solve this?
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view_it_on_GitHub, or mute_the_thread.


-- 
Damien Garaud
Data Scientist – Developer, Oslandia
http://oslandia.com
