### ISSUE TITLE
Improve the way to set the random seed in the data/arrays generator

### ISSUE THREAD

**Issue by garaud** [Oslandia/mapillary_classification#45]
For now, you cannot have a random data generator because the seed is set by default in the function.

I think you can have a `None` value. But we have to generate a random integer to set the seed when yo call the Keras function generators because you must have the same seed for the image training generator and label generator.

**Comment by delhomer** [comment]
Maybe we can draw a random integer starting from computer clock in the caller module (something like `train.py`, I guess), to ensure its unicity, and affect the same integer to both generator creations?

**Comment by garaud** [comment]
Exactly! I thought to the same thing.
Raphael Delhome writes:

> File "-", line 13, column 6: CDATA terminal not found
> File "-", line 13, column 6: CDATA terminal not found
> Maybe we can draw a random integer starting from computer clock in the
> caller module (something like train.py, I guess), to ensure its unicity,
> and affect the same integer to both generator creations?
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view_it_on_GitHub, or mute_the_thread.


-- 
Damien Garaud
Data Scientist – Developer, Oslandia
http://oslandia.com

**Comment by delhomer** [comment]
I will push a commit to pass `None` as the default value for `seed` parameter in `feed_generator` and `create_generator` functions. The remainder of the issue will be focused when developing a new version of `train.py`.

**Comment by delhomer** [comment]
I re-open this issue, as the current implementation is hardly wrong: a `None` seed does not guarantee that images are associed with their own labels.
