### ISSUE TITLE
Aerial dataset population improvement

### ISSUE THREAD

**Issue by delhomer** [Oslandia/mapillary_classification#91]
For now, the `populate` method for `AerialDataset` implements a double `for`-loop for image creation, and a similar `for`-loop for label computing.

One may think that both double loops may be simplified in a single one where operations on images and labels could be undertaken.

**Comment by garaud** [comment]
Maybe we can introduce the `abstractmethod` decorator on this method in the mother class. I think it's worth it.

**Comment by delhomer** [comment]
This decorator has been introduced with PR #88 . You could check at the module end: https://github.com/Oslandia/deeposlandia/blob/master/deeposlandia/datasets/__init__.py

**Comment by garaud** [comment]
Sorry, I didn't see it. Thanks.
