### ISSUE TITLE
Any pretrained model on  Mapillary Vistas Dataset 

### ISSUE THREAD

**Issue by robi56** [Oslandia/mapillary_classification#95]
Hi, This repository seems very interesting  .Any pretrained model on  **Mapillary Vistas Dataset**  is available?
Thanks

**Comment by delhomer** [comment]
Hello @robi56 ,
Unfortunately we did not release any pre-trained model, so as to respect their Terms of Use (see details on the [dataset website](https://www.mapillary.com/dataset/vistas) if you have not visited it yet).
Our advice here is to request Mapillary data on your side and train your own model, if possible. (Sorry if it looks unsatisfying).

Regarding other datasets, that is a good point, and we can plan to check if it possible in the next days.

**Comment by vpicavet** [comment]
@robi56 Should you be interested in a pre-trained model, we can work with Mapillary to get a commercial licence for the data and sell you our pre-trained model. Do not hesitate to contact Oslandia directly by email for details if interested.

**Comment by delhomer** [comment]
As @vpicavet answered, we can release pre-trained models for this dataset only under specific circumstances. The issue itself may be closed, do not hesitate to ask us for further details if interested.
